/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
//opencv
#include "opencv2/imgcodecs.hpp"
#include "opencv2/imgproc.hpp"
#include "opencv2/videoio.hpp"
#include <opencv2/highgui.hpp>
#include <opencv2/video.hpp>
//C
#include <stdio.h>
//C++
#include <iostream>
#include <sstream>

/* Header for class com_myapp_testjni_NativeClass */

using namespace cv;
using namespace std;
#ifndef _Included_com_myapp_testjni_NativeClass
#define _Included_com_myapp_testjni_NativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_myapp_testjni_NativeClass
 * Method:    squareDetection
 * Signature: (J)I
 */

 int thresh = 50, N = 11;

 void detectSquares(Mat& frame,vector<vector<Point> >& squares);

 void drawSq(Mat& frame,vector<vector<Point> >& squares);

 static double angle( Point pt1, Point pt2, Point pt0 );

 bool isSquare(Point p1, Point p2, Point p3, Point p4);

 float distSq(Point p,Point q);

 void detectSquaresNew(Mat& frame,vector<vector<Point> >& squares);

JNIEXPORT jint JNICALL Java_com_myapp_testjni_NativeClass_squareDetection
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
